config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :pics do
    member do
      put 'like', to: "pics#upvote"
    end
  end
  root 'pics#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pic.rb
class Pic < ApplicationRecord
  acts_as_votable
  belongs_to :user

  has_one_attached :image
  validates :image, content_type: /\Aimage\/.*\z/
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pics

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy, :upvote]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pics = Pic.all.order(created_at: :desc)
  end

  def new
    @pic = Pic.new
  end

  def show
  end

  def edit
  end

  def create
    @pic = Pic.new(pic_params)
    @pic.user = current_user

    if @pic.save
      redirect_to pic_path(@pic), notice: 'Pic created'
    else
      render 'new'
    end
  end

  def update
    if @pic.update(pic_params)
      redirect_to pic_path(@pic), notice: 'Pic updated'
    else
      render 'edit'
    end
  end

  def destroy
    @pic.image.purge
    @pic.destroy
    redirect_to root_path
  end

  def upvote
    @pic.upvote_by current_user
    redirect_to @pic
  end

  private

  def set_pic
    @pic = Pic.find(params[:id])
  end

  def pic_params
    params.require(:pic).permit(:title, :description, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/layouts/_prueba_bootstrap.html.haml
/ Button trigger modal
%button.btn.btn-primary{"data-bs-target" => "#exampleModal", "data-bs-toggle" => "modal", :type => "button"}
  Launch demo modal
/ Modal
#exampleModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title Modal title
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", :type => "button"}
      .modal-body
        \...
      .modal-footer
        %button.btn.btn-secondary{"data-bs-dismiss" => "modal", :type => "button"} Close
        %button.btn.btn-primary{:type => "button"} Save changes
%button.btn.btn-secondary{"data-bs-placement" => "top", "data-bs-toggle" => "tooltip", :title => "Tooltip on top", :type => "button"}
  Tooltip on top
%button.btn.btn-secondary{"data-bs-placement" => "right", "data-bs-toggle" => "tooltip", :title => "Tooltip on right", :type => "button"}
  Tooltip on right
%button.btn.btn-secondary{"data-bs-placement" => "bottom", "data-bs-toggle" => "tooltip", :title => "Tooltip on bottom", :type => "button"}
  Tooltip on bottom
%button.btn.btn-secondary{"data-bs-placement" => "left", "data-bs-toggle" => "tooltip", :title => "Tooltip on left", :type => "button"}
  Tooltip on left
%i.far.fa-address-book
%i.fab.fa-github

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GolfoSanJorge
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'favicon-32x32.png', sizes: '32x32', type: 'img/png'
    = favicon_link_tag 'favicon-16x16.png', sizes: '16x16', type: 'img/png'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg.navbar-dark
      .container
        .navbar-brand
          = link_to root_path, class: 'text-white text-decoration-none' do
            = image_tag('golfosanjorge.png', width: '200px')
        %ul.d-block.d-lg-none.user-menu.mobile
          - if user_signed_in?
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle{ href: '#', id: 'perfilDropDown', role: 'button', 'data-bs-toggle': 'dropdown', 'aria-expanded': 'false', class: 'rounded-circle' }
                %i.fas.fa-user
              %ul.dropdown-menu{ 'aria-labelledby': 'perfilDropdown' }
                %li.nav-item
                  = link_to 'Nuevo Post', new_pic_path, class: 'dropdown-item'
                %li.nav-item
                  = link_to 'Perfil', edit_user_registration_path, class: 'dropdown-item'
                %li.nav-item
                  = link_to 'Salir', destroy_user_session_path, method: :delete, class: 'dropdown-item'
          - else
            %li.nav-item.dropdown
              %a.nav-link.dropdown-toggle{ href: '#', id: 'perfilDropDown', role: 'button', 'data-bs-toggle': 'dropdown', 'aria-expanded': 'false', class: 'rounded-circle' }
                %i.fas.fa-user
              %ul.dropdown-menu{ 'aria-labelledby': 'perfilDropdown' }
                %li.nav-item
                  = link_to 'Registrarse', new_user_registration_path, class: 'dropdown-item'
                %li.nav-item
                  = link_to 'Entrar', new_user_session_path, class: 'dropdown-item'
        %button.navbar-toggler{ type: 'button', 'data-bs-toggle': 'collapse', 'data-bs-target': "#navbarSupportedContent", 'aria-controls': "navbarSupportedContent", 'aria-expanded': "false", 'aria-label': "Toggle navigation"}
          %span.navbar-toggler-icon
            %i.fas.fa-bars
        .collapse.navbar-collapse.justify-content-end{id: 'navbarSupportedContent'}
          %ul.navbar-nav
            %li.nav-item
              %a.nav-link{ href: '#' } Caleta Olivia
            %li.nav-item
              %a.nav-link{ href: '#' } Comodoro
            .d-none.d-lg-block.user-menu
              - if user_signed_in?
                %li.nav-item.dropdown
                  %a.nav-link.dropdown-toggle{ href: '#', id: 'perfilDropDown', role: 'button', 'data-bs-toggle': 'dropdown', 'aria-expanded': 'false', class: 'rounded-circle' }
                    %i.fas.fa-user
                  %ul.dropdown-menu{ 'aria-labelledby': 'perfilDropdown' }
                    %li.nav-item
                      = link_to 'Nuevo Post', new_pic_path, class: 'dropdown-item'
                    %li.nav-item
                      = link_to 'Perfil', edit_user_registration_path, class: 'dropdown-item'
                    %li.nav-item
                      = link_to 'Salir', destroy_user_session_path, method: :delete, class: 'dropdown-item'

              - else
                %li.nav-item.dropdown
                  %a.nav-link.dropdown-toggle{ href: '#', id: 'perfilDropDown', role: 'button', 'data-bs-toggle': 'dropdown', 'aria-expanded': 'false', class: 'rounded-circle' }
                    %i.fas.fa-user
                  %ul.dropdown-menu{ 'aria-labelledby': 'perfilDropdown' }
                    %li.nav-item
                      = link_to 'Registrarse', new_user_registration_path, class: 'dropdown-item'
                    %li.nav-item
                      = link_to 'Entrar', new_user_session_path, class: 'dropdown-item'

    .container.mt-5
      - flash.each do |name, msg|
        = content_tag :div, msg, class: 'alert alert-info', role: 'alert'
      = yield

    %script{:charset => "utf-8", :type => "text/javascript"}
      $(document).ready(function(){
      console.log('jquery funciona');
      AOS.init();
      });

app/views/pics/_form.html.haml
= simple_form_for @pic, html: { multipart: true } do |f|
  -if @pic.errors.any?
    #errors
      %h2
        =  "#{pluralize(@pic.errors.count, 'error')} prevented this Pic from saving"
      %ul
        - @pic.errors.full_messages.each do |msg|
          %li
            = msg
  .mb-3
    = f.label 'Imagen', class: 'form-label-sm'
    = f.input :image, as: :file, input_html: { type: 'file', class: 'form-control' }, direct_upload: true, label: false
  .mb-3
    = f.label 'Título', class: 'form-label-sm'
    = f.input :title, input_html: { class: 'form-control' }, label: false
  .mb-3
    = f.label 'Descripción', class: 'form-label-sm'
    = f.input :description, input_html: { class: 'form-control', rows: '10' }, label: false
  .mb-3
    = f.button :submit, @pic.new_record? ? 'Crear Post' : 'Guardar Post', class: 'btn btn-info'

app/views/pics/edit.html.haml
.container
  #edit_page.offset-md-2.col-md-8.bg-light.p-3
    %h1.mb-5 Edit Pic
    = render 'form'
    = link_to 'Cancelar', pic_path(@pic)

app/views/pics/index.html.haml
.row
  - @pics.each do |pic|
    .col-lg-3.col-md-4.col-sm-6
      .card.mb-4{'data-aos': 'fade-up', 'data-aos-offset': "-50", 'data-aos-delay': "50", 'data-aos-duration': "500", 'data-aos-easing': "ease-in", 'data-aos-mirror': "true", 'data-aos-once': "true", 'data-aos-anchor-placement': "top-center"}
        = link_to pic do
          - if pic.image.attached?
            .text-center
              = cl_image_tag pic.image.key, class: 'img-fluid card_img-top'
          .card-body
            .card-title
              %h2.text-left
                = pic.title
              %p.small #{ time_ago_in_words(pic.created_at).capitalize }

app/views/pics/new.html.haml
.container
  .offset-md-2.col-md-8.bg-light.p-3
    %h1.mb-5 Post Pic
    = render 'form'
    = link_to 'Volver', root_path

app/views/pics/show.html.haml
.offset-xl-3.col-xl-6.offset-md-2.col-md-8
  .card
    - if @pic.image.attached?
      .text-center.mb-5
        = cl_image_tag @pic.image.key, class: 'img-fluid'

    .card-body
      .card-title.mb-5
        .container
          %h1.mb-5
            = @pic.title
          %p.text-justify
            = @pic.description

      .card-footer
        .row
          .col-md-6
            %p.text-bold.mb-0
              = @pic.user.email
          .col-md-6.flex-end
            = link_to like_pic_path(@pic), method: :put, class: 'btn btn-outline-primary vote-button' do
              %i.fa-regular.fa-thumbs-up
                = @pic.get_upvotes.size if  @pic.get_upvotes.size > 0
            - if user_signed_in? && @pic.user_id == current_user.id
              = link_to 'Editar', edit_pic_path, class: 'btn btn-info text-white edit-button'
              = link_to 'Borrar', pic_path, method: :delete, data: { confirm: '¿Quiéres borrar tu post?' }, class: 'btn btn-danger delete-button'